model:
  name: SIREN
  args:
    dim_in:                     2
    dim_hidden:                 512
    dim_out:                    3
    num_layers:                 12
    w0_initial:                 30.